### ISSUE TITLE
[Feature Request] Alpine linux binaries

### ISSUE THREAD

**Issue by dillionverma** [p2pderivatives/cfd-dlc-js#57]
Hi 👋🏼,

Is it possible to add alpine linux binaries to the https://github.com/cryptogarageinc/cfd-dlc-js repo? It would help us significantly reduce our production docker image sizes.

I would assume that the work required for this would be very similar to this PR: https://github.com/cryptogarageinc/cfd-js/pull/263

**Comment by Tibo-lg** [comment]
Hi @dillionverma 

I had a quick look, but I think it's not straightforward to port https://github.com/cryptogarageinc/cfd-js/pull/263 to this repo because the CI for cfd-js has become quite different than the one here. Also while I understand it'd be nice to have the binaries available here, can't you just upload your image to use alpine instead of whatever you're using now?

**Comment by dillionverma** [comment]
Hey @Tibo-lg!

Thanks for taking a look. We've decided that this isn't as high of a priority for us anymore as there are some other libraries which limit our ability to use alpine linux as well. The original goal here was just to reduce final docker image size but we've reached a state where we are content with what we have now.
